platform: linux

image_resource:
  type: docker-image

inputs:
- name: pxf_src
- name: pxf_tarball
- name: ccp_src
- name: cluster_env_files
- name: terraform
- name: terraform_dataproc
  optional: true
- name: dataproc_env_files
  optional: true
- name: dataproc_2_env_files
  optional: true

params:
  GP_VER:
  IMPERSONATION: true
  INSTALL_GPHDFS: true
  KERBEROS: false
  PXF_BASE_DIR:
  PXF_COMPONENT: true
  PXF_JVM_OPTS:
  SKIP_HADOOP_SETUP:

run:
  path: sh
  args:
  - -exc
  - |
    ccp_src/scripts/setup_ssh_to_cluster.sh || exit 1
    pxf_src/concourse/scripts/install_pxf.bash
